import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import axios from "axios";
import GoogleAutoComplete from "../src/components/Profile/GoogleAutoComplete";
import { login } from "../src/Store/MiddleWare/authMiddleware";
import Link from "next/link";

export default function  Home() {


  return (
    <div className={styles.container}>
      <Head>

        <title>CitiSkopes</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/auth/login">CitiSkope</Link>
        </h1>
       
      
      </main>

    
    </div>
  );
}

